name: simple_dart_dropdown
description: Dropdown Component
version: 0.0.1
repository: https://github.com/simple-dart/dropdown
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_modal_controller: ^0.0.7
  simple_dart_ui_core: ^0.0.3
